# zshoptions.plugin.zsh: Configure preferred options for an interactive shell

# If this is not an interactive shell, abort.
case "$-" in
  (*i*) ;;
    (*) return ;;
esac

setopt noallexport
setopt alwaystoend
setopt appendcreate
setopt autocd
setopt autocontinue
setopt autonamedirs
setopt autopushd
setopt autoresume
setopt nobashautolist
setopt nobashrematch
setopt nobeep
setopt braceccl
setopt nobsdecho
setopt caseglob
setopt casepaths
setopt cbases
setopt cdablevars
setopt nochasedots
setopt chaselinks
setopt noclobber
setopt combiningchars
setopt completealiases
setopt completeinword
setopt nocontinueonerror
setopt correct
setopt nocorrectall
setopt nocshjunkiehistory
setopt nocshjunkieloops
setopt nocshjunkiequotes
setopt nocshnullcmd
setopt nocshnullglob
setopt extendedglob
setopt extendedhistory
setopt noforcefloat
setopt noglobassign
setopt globcomplete
setopt noglobdots
setopt globstarshort
setopt noglobsubst
setopt hashexecutablesonly
setopt nohistallowclobber
setopt histexpiredupsfirst
setopt histfcntllock
setopt histfindnodups
setopt histignorealldups
setopt histignoredups
setopt histignorespace
setopt histlexwords
setopt nohistnofunctions
setopt histnostore
setopt histreduceblanks
setopt histsavenodups
setopt histsubstpattern
setopt histverify
setopt noignorebraces
setopt noignoreclosebraces
setopt noignoreeof
setopt noincappendhistory
setopt noincappendhistorytime
setopt interactivecomments
setopt noksharrays
setopt nokshautoload
setopt nokshglob
setopt nokshoptionprint
setopt nokshtypeset
setopt nokshzerosubscript
setopt listambiguous
setopt nolistpacked
setopt nolocaloptions
setopt longlistjobs
setopt nomagicequalsubst
setopt nomailwarning
setopt nomarkdirs
setopt nomenucomplete
setopt nomultifuncdef
setopt nonullglob
setopt numericglobsort
setopt nooctalzeroes
setopt nooverstrike
setopt nopathdirs
setopt nopathscript
setopt nopipefail
setopt noposixaliases
setopt noposixargzero
setopt noposixbuiltins
setopt noposixcd
setopt noposixidentifiers
setopt noposixjobs
setopt noposixstrings
setopt noposixtraps
setopt noprinteightbit
setopt noprintexitvalue
# setopt promptbang
setopt promptsubst
setopt pushdignoredups
setopt pushdminus
setopt nopushdsilent
setopt pushdtohome
setopt rcexpandparam
setopt rcquotes
setopt norecexact
setopt rematchpcre
setopt norestricted
setopt rmstarsilent
setopt normstarwait
setopt sharehistory
setopt noshfileexpansion
setopt noshglob
setopt noshnullcmd
setopt noshoptionletters
setopt noshwordsplit
setopt nosinglecommand
setopt nosinglelinezle
setopt nosourcetrace
setopt nosunkeyboardhack
setopt notransientrprompt
# setopt warncreateglobal
# setopt warnnestedvar
