# zshoptions.plugin.zsh: Configure preferred options for an interactive shell

# If this is not an interactive shell, abort.
return
case "$-" in
  (*i*) ;;
    (*) return ;;
esac

setopt aliases
setopt alwayslastprompt
setopt alwaystoend
setopt alwaystoend
setopt appendcreate
setopt appendhistory
setopt autocd
setopt autocontinue
setopt autocontinue
setopt autolist
setopt automenu
setopt autonamedirs
setopt autonamedirs
setopt autoparamkeys
setopt autoparamslash
setopt autopushd
setopt autopushd
setopt autoremoveslash
setopt autoresume
setopt autoresume
setopt badpattern
setopt banghist
setopt bareglobqual
setopt bgnice
setopt braceccl
setopt caseglob
setopt casematch
setopt cbases
setopt cbases
setopt cdablevars
setopt chaselinks
setopt checkjobs
setopt completeinword
setopt completeinword
setopt correct
setopt correct
setopt cprecedences
setopt debugbeforecmd
setopt equals
setopt evallineno
setopt exec
setopt extendedglob
setopt extendedhistory
setopt extendedhistory
setopt functionargzero
setopt glob
setopt globalrcs
setopt globcomplete
setopt globcomplete
setopt globstarshort
setopt hashcmds
setopt hashdirs
setopt hashexecutablesonly
setopt hashexecutablesonly
setopt hashlistall
setopt histbeep
setopt histexpiredupsfirst
setopt histexpiredupsfirst
setopt histfcntllock
setopt histfcntllock
setopt histfindnodups
setopt histfindnodups
setopt histignorealldups
setopt histignorealldups
setopt histignoredups
setopt histignoredups
setopt histignorespace
setopt histignorespace
setopt histlexwords
setopt histlexwords
setopt histnostore
setopt histnostore
setopt histreduceblanks
setopt histreduceblanks
setopt histsavebycopy
setopt histsavenodups
setopt histsavenodups
setopt histsubstpattern
setopt histverify
setopt histverify
setopt hup
setopt incappendhistory
setopt incappendhistory
setopt interactive
setopt interactivecomments
setopt interactivecomments
setopt listambiguous
setopt listbeep
setopt listtypes
setopt localoptions
setopt localpatterns
setopt localtraps
setopt longlistjobs
setopt longlistjobs
setopt monitor
setopt monitor
setopt multibyte
setopt multifuncdef
setopt multios
setopt nobeep
setopt noflowcontrol
setopt nomatch
setopt notify
setopt numericglobsort
setopt promptcr
setopt promptpercent
setopt promptsp
setopt promptsubst
setopt promptsubst
setopt pushdignoredups
setopt pushdminus
setopt pushdtohome
setopt rcexpandparam
setopt rcquotes
setopt rcs
setopt rematchpcre
setopt rematchpcre
setopt rmstarsilent
setopt rmstarsilent
setopt sharehistory
setopt sharehistory
setopt shinstdin
setopt shortloops
setopt unset
setopt zle
setopt zle
unsetopt aliasfuncdef
unsetopt allexport
unsetopt bashautolist
unsetopt bashrematch
unsetopt bsdecho
unsetopt chasedots
unsetopt clobber
unsetopt combiningchars
unsetopt completealiases
unsetopt continueonerror
unsetopt correctall
unsetopt cshjunkiehistory
unsetopt cshjunkieloops
unsetopt cshjunkiequotes
unsetopt cshnullcmd
unsetopt cshnullglob
unsetopt dvorak
unsetopt emacs
unsetopt errexit
unsetopt errreturn
unsetopt forcefloat
unsetopt globalexport
unsetopt globassign
unsetopt globdots
unsetopt globsubst
unsetopt histallowclobber
unsetopt histnofunctions
unsetopt ignorebraces
unsetopt ignoreclosebraces
unsetopt ignoreeof
unsetopt incappendhistorytime
unsetopt ksharrays
unsetopt kshautoload
unsetopt kshglob
unsetopt kshoptionprint
unsetopt kshtypeset
unsetopt kshzerosubscript
unsetopt listpacked
unsetopt listrowsfirst
unsetopt localloops
unsetopt localoptions
unsetopt localpatterns
unsetopt localtraps
unsetopt magicequalsubst
unsetopt mailwarning
unsetopt markdirs
unsetopt menucomplete
unsetopt nullglob
unsetopt octalzeroes
unsetopt overstrike
unsetopt pathdirs
unsetopt pathscript
unsetopt pipefail
unsetopt posixaliases
unsetopt posixargzero
unsetopt posixbuiltins
unsetopt posixcd
unsetopt posixidentifiers
unsetopt posixjobs
unsetopt posixstrings
unsetopt posixtraps
unsetopt printeightbit
unsetopt printexitvalue
unsetopt privileged
unsetopt promptbang
unsetopt pushdsilent
unsetopt recexact
unsetopt restricted
unsetopt rmstarwait
unsetopt shfileexpansion
unsetopt shglob
unsetopt shnullcmd
unsetopt shoptionletters
unsetopt shwordsplit
unsetopt singlecommand
unsetopt singlelinezle
unsetopt sourcetrace
unsetopt sunkeyboardhack
unsetopt transientrprompt
unsetopt trapsasync
unsetopt typesetsilent
unsetopt verbose
unsetopt vi
unsetopt warncreateglobal
unsetopt warnnestedvar
unsetopt xtrace
